-- Table structure for table `review`
CREATE TABLE IF NOT EXISTS public.review (
    review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_text TEXT NOT NULL,
    review_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    inv_id INTEGER NOT NULL,
    account_id INTEGER NOT NULL,
    CONSTRAINT fk_inventory_review FOREIGN KEY (inv_id)
        REFERENCES public.inventory (inv_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_account_review FOREIGN KEY (account_id)
        REFERENCES public.account (account_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
